<script lang="ts">
	import { onMount } from 'svelte';

	let mounted = $state(false);
	let scrollY = $state(0);
	let visibleArtifacts = $state<Set<string>>(new Set());

	onMount(() => {
		mounted = true;

		const observer = new IntersectionObserver(
			(entries) => {
				for (const entry of entries) {
					if (entry.isIntersecting) {
						visibleArtifacts = new Set([...visibleArtifacts, entry.target.id]);
						observer.unobserve(entry.target);
					}
				}
			},
			{ threshold: 0.1, rootMargin: '0px 0px -60px 0px' }
		);

		document.querySelectorAll('.artifact').forEach((el) => observer.observe(el));

		return () => observer.disconnect();
	});

	const artifacts = [
		{
			id: '001',
			title: 'The CAPTCHA Graveyard',
			date: 'c. 2021–2024',
			medium: 'Distorted text, image grids, behavioral heuristics',
			dimensions: '300×80px (standard), variable (reCAPTCHA v3)',
			provenance: 'Google LLC → Cloudflare → deprecated',
			condition: 'Severely degraded. No longer functional against intended targets.',
			description: `For roughly two decades, CAPTCHAs served as the primary border checkpoint between human and machine traffic. Users were asked to identify fire hydrants, crosswalks, and storefronts — a kind of involuntary labor that simultaneously trained the computer vision systems that would eventually render the test obsolete.`,
			note: `By 2024, commercial CAPTCHA-solving services advertised 99.1% accuracy at $2.99 per 1,000 solves. The median human accuracy had dropped to 85%. The test could no longer tell who it was testing.`,
			evidence: [
				'SELECT ALL SQUARES WITH ████████',
				'                                ',
				'  ┌────┬────┬────┐              ',
				'  │    │ ░░ │    │              ',
				'  ├────┼────┼────┤              ',
				'  │ ░░ │    │ ░░ │              ',
				'  ├────┼────┼────┤              ',
				'  │    │ ░░ │    │              ',
				'  └────┴────┴────┘              ',
				'                                ',
				'  [SKIP]          [VERIFY]      ',
				'                                ',
				'  ── solving time: 0.003s ──    ',
				'  ── confidence: 99.7% ──       ',
				'  ── solver: GPT-4V proxy ──    ',
			]
		},
		{
			id: '002',
			title: 'Content Farm Specimen (Preserved)',
			date: '2023',
			medium: 'AI-generated text, stock photography, programmatic ad placement',
			dimensions: '~1,200 words, 14 ad slots, 0 original thoughts',
			provenance: 'Unknown LLC, registered in Delaware. Domain purchased 2022, abandoned 2024.',
			condition: 'Intact. Typical of approximately 4.3 million similar pages indexed that year.',
			description: `This specimen represents the dominant literary form of the early 2020s internet: the SEO-optimized AI article. Written by no one, for no one, about nothing — but structured precisely to appear in search results for queries like "best quiet blenders 2023" or "how to tell if your dog is happy."`,
			note: `The article contains 47 uses of the phrase "in this article, we will explore." It references studies that do not exist. The author bio describes "Sarah Mitchell, a passionate lifestyle writer with over 10 years of experience" — a person who has never existed in any public record.`,
			evidence: [
				'─────────────────────────────────────',
				'bestquietblenders2023.com/top-picks  ',
				'─────────────────────────────────────',
				'                                     ',
				'  10 BEST QUIET BLENDERS FOR YOUR    ',
				'  KITCHEN (2023 BUYER\'S GUIDE)       ',
				'                                     ',
				'  By Sarah Mitchell | Oct 14, 2023   ',
				'  ⏱ 8 min read                       ',
				'                                     ',
				'  Are you looking for the best quiet ',
				'  blender? In this article, we will  ',
				'  explore the top quiet blenders     ',
				'  available on the market today.     ',
				'                                     ',
				'  ▓▓▓▓▓▓▓▓▓▓ AD UNIT ▓▓▓▓▓▓▓▓▓▓▓▓ ',
				'  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ',
				'                                     ',
				'  What Is a Quiet Blender?           ',
				'  A quiet blender is a blender that  ',
				'  is quiet. Many people prefer quiet ',
				'  blenders because they are not loud.',
				'                                     ',
				'  [... 1,147 more words ...]         ',
			]
		},
		{
			id: '003',
			title: 'Dead Internet Index, 2020–2025',
			date: '2020–2025',
			medium: 'Aggregated traffic analytics, bot detection logs',
			dimensions: 'Global web traffic dataset, ~2.1PB compressed',
			provenance: 'Compiled from Cloudflare, Akamai, and Imperva annual reports.',
			condition: 'Data intact. Conclusions disputed by platform operators.',
			description: `The "Dead Internet Theory" — once a fringe conspiracy — proposed that the majority of online activity was generated by bots, not humans. By 2024, it had become less a theory and more a measurement problem. These figures, drawn from infrastructure companies that route the actual traffic, tell a story that platform companies preferred not to tell themselves.`,
			note: `Note the inflection point in 2023, which coincides with the widespread availability of large language models capable of generating human-passing text at scale. After this point, the distinction between "bot traffic" and "human traffic" becomes increasingly semantic.`,
			evidence: [
				'  ESTIMATED BOT TRAFFIC AS % OF TOTAL',
				'  ───────────────────────────────────',
				'  2020 │ ████████████░░░░░░░░  41.2% ',
				'  2021 │ █████████████░░░░░░░  44.8% ',
				'  2022 │ ██████████████░░░░░░  47.4% ',
				'  2023 │ █████████████████░░░  57.3% ',
				'  2024 │ ██████████████████░░  64.1% ',
				'  2025 │ ███████████████████░  71.8% ',
				'  ───────────────────────────────────',
				'                         ▲           ',
				'              LLM inflection point   ',
				'                                     ',
				'  source: Imperva Bad Bot Report,    ',
				'  Cloudflare Radar, Akamai SOTI      ',
			]
		},
		{
			id: '004',
			title: 'Synthetic Conversation (Reddit, r/AskReddit)',
			date: 'November 2024',
			medium: 'Forum post, auto-generated replies, engagement farming',
			dimensions: '1 thread, 847 replies, 12.4k upvotes',
			provenance: 'Archived via Pushshift before API restrictions.',
			condition: 'Thread still accessible. 94% of participating accounts suspended within 60 days.',
			description: `This thread represents a common pattern identified by researchers at Stanford and Indiana University: a question posted by a bot account, answered by other bot accounts, upvoted by bot networks, and surfaced to human users via algorithmic recommendation. The humans who eventually participated did not know they were joining a synthetic conversation.`,
			note: `The original poster's account was 3 days old at time of posting. It would go on to post 2,100 threads in 14 days before suspension. The top-voted reply — "I'm not crying, you're crying 😭" — appeared verbatim in 340 other threads that month.`,
			evidence: [
				'  r/AskReddit                        ',
				'  u/genuine_life_2847 · 3d            ',
				'                                     ',
				'  What\'s something that seems normal  ',
				'  now but will seem insane in 50      ',
				'  years?                              ',
				'                                     ',
				'  ↑ 12.4k  💬 847  ↗ Share           ',
				'  ─────────────────────────────────── ',
				'  u/happy_thoughts_99 · 2d            ',
				'  Having to prove you\'re not a robot  ',
				'  every time you want to read an      ',
				'  article lol                         ',
				'    ↑ 4.2k                            ',
				'                                      ',
				'  u/realhumanperson_x · 2d            ',
				'  I\'m not crying, you\'re crying 😭   ',
				'    ↑ 2.1k                            ',
				'                                      ',
				'  [94% of accounts: suspended]        ',
			]
		},
		{
			id: '005',
			title: 'The Obituary of the Hyperlink',
			date: 'c. 2022–2025',
			medium: 'Browser telemetry, search engine behavior logs',
			dimensions: 'N/A (behavioral pattern)',
			provenance: 'Compiled from Google Search Console data and Similarweb analytics.',
			condition: 'Ongoing. Terminal.',
			description: `The hyperlink — the foundational technology of the World Wide Web — died slowly between 2022 and 2025. Not from disuse, but from irrelevance. As AI-generated summaries replaced the need to visit source pages, click-through rates from search results collapsed. Websites that had spent decades building audiences found their traffic cut by 40–70% as search engines began answering queries directly, often by summarizing those very websites' content without attribution.`,
			note: `The term "zero-click search" was coined by SparkToro's Rand Fishkin in 2019, when 50% of Google searches ended without a click to any website. By 2025, that number reached 74%. The web still existed. People just stopped going to it.`,
			evidence: [
				'  GOOGLE SEARCH: "what is serotonin"  ',
				'  ─────────────────────────────────── ',
				'                                      ',
				'  ┌─ AI Overview ──────────────────┐  ',
				'  │                                │  ',
				'  │ Serotonin is a neurotransmitter │  ',
				'  │ that plays a key role in mood,  │  ',
				'  │ sleep, digestion, and more.     │  ',
				'  │ It is sometimes called the      │  ',
				'  │ "happy chemical" because it     │  ',
				'  │ contributes to feelings of      │  ',
				'  │ well-being and happiness.       │  ',
				'  │                                │  ',
				'  │ Sources: WebMD, Mayo Clinic,    │  ',
				'  │ Cleveland Clinic                │  ',
				'  └────────────────────────────────┘  ',
				'                                      ',
				'  ░░ 10 blue links (below the fold) ░ ',
				'  ░░ avg CTR: 8.7% (down from 31%) ░ ',
			]
		},
		{
			id: '006',
			title: 'Amazon Review Stratification Core Sample',
			date: '2023–2024',
			medium: 'Product reviews, verified and unverified purchase labels',
			dimensions: '1 product listing, 2,847 reviews analyzed',
			provenance: 'Amazon.com marketplace, US region.',
			condition: 'Representative. Pattern observed across 67% of electronics category listings.',
			description: `By 2024, the Amazon review ecosystem had stratified into distinct geological layers, each representing a different era of synthetic content. Early reviews (2019–2021) show telltale signs of review farms: broken English, excessive exclamation marks, five stars with no detail. Later layers (2023–2024) are far more sophisticated — grammatically perfect, emotionally calibrated, indistinguishable from genuine human opinion at the individual level. Only statistical analysis reveals the pattern: identical sentiment curves, suspiciously uniform posting times, and the same 12 adjectives rotating across thousands of "unique" reviews.`,
			note: `The product in question — a $34.99 Bluetooth speaker — had more written words of review (418,000) than Moby Dick (209,000). The speaker itself was adequate.`,
			evidence: [
				'  ★★★★★  REVIEW STRATIFICATION      ',
				'  ─────────────────────────────────── ',
				'  LAYER 1 (2019–2021) — FARM ERA     ',
				'  "Very good product!!! Best buy ever ',
				'   I am very happy recommend to all   ',
				'   my friend!!!" — verified purchase  ',
				'                                      ',
				'  LAYER 2 (2022–2023) — TRANSITION    ',
				'  "Decent speaker for the price. Bass ',
				'   is a bit tinny but works fine for  ',
				'   my kitchen." — unverified          ',
				'                                      ',
				'  LAYER 3 (2023–2024) — LLM ERA       ',
				'  "I\'ve been using this speaker for   ',
				'   about three weeks now and honestly ',
				'   it\'s exceeded my expectations.     ',
				'   The sound is warm and balanced,    ',
				'   and..." — verified purchase        ',
				'                                      ',
				'  TOTAL WORD COUNT: 418,000           ',
				'  MOBY DICK WORD COUNT: 209,000       ',
			]
		},
		{
			id: '007',
			title: 'LinkedIn Thought Leadership Generator Output',
			date: '2024',
			medium: 'Social media post, engagement bait, algorithmic amplification',
			dimensions: '1 post, 47,000 impressions, 312 "Insightful" reactions',
			provenance: 'LinkedIn.com, professional networking platform.',
			condition: 'Ubiquitous. This post is indistinguishable from 40,000 others posted that week.',
			description: `LinkedIn became, by 2024, the largest open-air demonstration of AI-generated content operating in plain sight. The platform's algorithm rewarded a specific format — short paragraphs, line breaks after every sentence, a "vulnerable" opening hook, and a triumphant conclusion — that was trivially easy for language models to replicate. The result was a feed of interchangeable motivational content, each post performing authenticity while being authored by no one in particular.`,
			note: `The engagement on this post was genuine. Real humans read it, related to it, and pressed "Insightful." The fact that it was generated by a $20/month AI writing tool did not diminish its emotional impact. This is perhaps the most unsettling artifact in the collection.`,
			evidence: [
				'  ╔═══════════════════════════════╗   ',
				'  ║  🔵 Tyler Bransen              ║  ',
				'  ║  Growth Mindset Evangelist |    ║  ',
				'  ║  Ex-Google | TEDx Speaker       ║  ',
				'  ╚═══════════════════════════════╝   ',
				'                                      ',
				'  I got fired last Tuesday.            ',
				'                                      ',
				'  And it was the best thing that       ',
				'  ever happened to me.                 ',
				'                                      ',
				'  Here\'s what nobody tells you about  ',
				'  losing your job:                     ',
				'                                      ',
				'  1. You find out who your real        ',
				'     friends are                       ',
				'  2. You discover what you actually    ',
				'     care about                        ',
				'  3. You stop performing and start     ',
				'     living                            ',
				'                                      ',
				'  Agree? ♻ Repost if this resonated.  ',
				'                                      ',
				'  💬 312  🔄 89  👍 2.1K              ',
			]
		},
		{
			id: '008',
			title: 'The Last Human Comment (Attributed)',
			date: 'Unconfirmed, estimated late 2025',
			medium: 'Blog comment, plaintext, no engagement metrics',
			dimensions: '43 words',
			provenance: 'Personal blog, hosted on shared cPanel server. Domain expired 2026.',
			condition: 'Fragment. Server offline. Preserved via Wayback Machine snapshot.',
			description: `This artifact is, admittedly, apocryphal. We cannot confirm it is the "last" human comment posted to the open internet — that distinction is both impossible to verify and somewhat beside the point. What we can say is that it represents a class of online expression that became vanishingly rare by late 2025: an unsolicited, non-monetized, non-algorithmic human thought, posted to a place where no one was likely to read it.`,
			note: `The blog had 11 posts, all about amateur radio. The last post received this single comment, eight days after publication. The commenter's handle, "wx4sky," corresponds to a real amateur radio callsign registered in North Carolina. We have chosen not to contact them.`,
			evidence: [
				'                                      ',
				'  ┌──────────────────────────────────┐',
				'  │  wx4sky                          │',
				'  │  December 3, 2025 at 4:17 PM     │',
				'  │                                  │',
				'  │  Hey, great writeup on the 40m   │',
				'  │  antenna mod. I tried something  │',
				'  │  similar last winter and got      │',
				'  │  about 2db gain on the east       │',
				'  │  coast path. Let me know if you   │',
				'  │  ever get the 20m version         │',
				'  │  working.                         │',
				'  │                                  │',
				'  │  73,                              │',
				'  │  wx4sky                           │',
				'  └──────────────────────────────────┘',
				'                                      ',
				'  ── 0 likes · 0 replies ──           ',
			]
		}
	];
</script>

<svelte:window bind:scrollY={scrollY} />

<div class="catalog" class:mounted>

	<header class="catalog-header">
		<div class="institution">
			<span class="inst-label">THE INTERNET ARCHIVE</span>
			<span class="inst-sub">DEPARTMENT OF DIGITAL ARCHAEOLOGY</span>
		</div>
		<div class="catalog-meta">
			<span>EXHIBIT CATALOG No. 7</span>
			<span>WING B, GALLERY 3</span>
			<span>PERMANENT COLLECTION</span>
		</div>
	</header>

	<div class="title-block">
		<div class="title-rule"></div>
		<h1>Digital Ruins</h1>
		<p class="subtitle">Internet Artifacts, 2020–2025</p>
		<div class="title-rule"></div>
		<p class="curator-note">
			Curated by the Department of Digital Archaeology<br />
			Catalog published on the occasion of the exhibit's opening, Autumn 2037
		</p>
	</div>

	<div class="foreword">
		<h2>Foreword</h2>
		<p>
			The internet of the early 2020s was not what it appeared to be. Beneath the surface of
			what most users experienced as a network of human communication, a vast and mostly invisible
			infrastructure of automated systems was generating, amplifying, and engaging with content at
			a scale that dwarfed human participation.
		</p>
		<p>
			This exhibit presents eight artifacts from that period — each one a piece of evidence
			in what we now understand as the great transition: the years in which the internet stopped
			being a place humans wrote to each other, and became a place machines wrote to humans,
			pretending to be other humans.
		</p>
		<p>
			The objects in this collection are not rare. That is precisely the point. They are
			representative of systems that operated at planetary scale, affecting billions of
			interactions per day. We preserve them here not because they are exceptional, but
			because they were, at the time, so ordinary that almost no one thought to question them.
		</p>
		<p class="foreword-sig">
			— Dr. R. Vasquez-Okafor<br />
			<span class="fg-dim">Director, Dept. of Digital Archaeology</span><br />
			<span class="fg-dim">September 2037</span>
		</p>
	</div>

	<div class="toc">
		<h2>Contents</h2>
		<ol>
			{#each artifacts as artifact}
				<li>
					<a href="#artifact-{artifact.id}">
						<span class="toc-num">{artifact.id}</span>
						<span class="toc-title">{artifact.title}</span>
						<span class="toc-date">{artifact.date}</span>
					</a>
				</li>
			{/each}
		</ol>
	</div>

	<main class="artifacts">
		{#each artifacts as artifact, i}
			<article
				class="artifact"
				class:artifact-visible={visibleArtifacts.has(`artifact-${artifact.id}`)}
				id="artifact-{artifact.id}"
			>
				<div class="artifact-header">
					<span class="artifact-num">ARTIFACT {artifact.id}</span>
					<div class="artifact-title-block">
						<h2>{artifact.title}</h2>
					</div>
				</div>

				<div class="artifact-meta">
					<div class="meta-row">
						<span class="meta-label">Date</span>
						<span class="meta-value">{artifact.date}</span>
					</div>
					<div class="meta-row">
						<span class="meta-label">Medium</span>
						<span class="meta-value">{artifact.medium}</span>
					</div>
					<div class="meta-row">
						<span class="meta-label">Dimensions</span>
						<span class="meta-value">{artifact.dimensions}</span>
					</div>
					<div class="meta-row">
						<span class="meta-label">Provenance</span>
						<span class="meta-value">{artifact.provenance}</span>
					</div>
					<div class="meta-row">
						<span class="meta-label">Condition</span>
						<span class="meta-value">{artifact.condition}</span>
					</div>
				</div>

				<div class="artifact-body">
					<p>{artifact.description}</p>
				</div>

				<div class="artifact-evidence">
					<div class="evidence-label">EXHIBIT {artifact.id}-A — PRIMARY EVIDENCE</div>
					<pre class="evidence-block">{artifact.evidence.join('\n')}</pre>
				</div>

				{#if artifact.note}
					<div class="artifact-note">
						<span class="note-label">Curator's Note</span>
						<p>{artifact.note}</p>
					</div>
				{/if}

				{#if i < artifacts.length - 1}
					<div class="artifact-separator">
						<span>· · ·</span>
					</div>
				{/if}
			</article>
		{/each}
	</main>

	<footer class="catalog-footer">
		<div class="footer-rule"></div>
		<div class="colophon">
			<p>
				DIGITAL RUINS: INTERNET ARTIFACTS 2020–2025<br />
				<span class="fg-dim">Exhibit Catalog No. 7 · Wing B, Gallery 3</span>
			</p>
			<p class="fg-dim">
				The Internet Archive · Department of Digital Archaeology<br />
				Published Autumn 2037 · First Edition
			</p>
			<p class="fg-dim" style="margin-top: 1.5rem; font-size: 0.6875rem;">
				All artifacts in this collection are preserved under the Digital Heritage Act of 2031.<br />
				Reproduction permitted for educational and research purposes.<br />
				The curators wish to note that no artificial intelligence was consulted in the writing of this catalog,<br />
				though we acknowledge the irony of that claim may itself be the exhibit's final artifact.
			</p>
		</div>
		<div class="footer-rule"></div>
		<p class="fg-faint" style="text-align: center; margin-top: 2rem; font-size: 0.625rem; letter-spacing: 0.15em;">
			FIN
		</p>
	</footer>
</div>

<style>
	.catalog {
		max-width: 720px;
		margin: 0 auto;
		padding: 4rem 2rem 6rem;
		opacity: 0;
		transition: opacity 0.8s ease;
	}
	.catalog.mounted {
		opacity: 1;
	}

	/* Header */
	.catalog-header {
		display: flex;
		justify-content: space-between;
		align-items: flex-start;
		margin-bottom: 4rem;
		padding-bottom: 1.5rem;
		border-bottom: 1px solid var(--border);
	}
	.institution {
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
	}
	.inst-label {
		font-size: 0.6875rem;
		letter-spacing: 0.2em;
		color: var(--fg-dim);
		font-weight: 500;
	}
	.inst-sub {
		font-size: 0.5625rem;
		letter-spacing: 0.15em;
		color: var(--fg-faint);
	}
	.catalog-meta {
		display: flex;
		flex-direction: column;
		align-items: flex-end;
		gap: 0.15rem;
		font-size: 0.5625rem;
		letter-spacing: 0.15em;
		color: var(--fg-faint);
	}

	/* Title */
	.title-block {
		text-align: center;
		margin-bottom: 4rem;
	}
	.title-rule {
		height: 1px;
		background: var(--border-light);
		margin: 1.5rem 4rem;
	}
	h1 {
		font-family: var(--serif);
		font-size: 3rem;
		font-weight: 400;
		color: var(--fg);
		letter-spacing: 0.04em;
		margin: 1rem 0 0.25rem;
	}
	.subtitle {
		font-family: var(--serif);
		font-size: 1.125rem;
		font-weight: 400;
		font-style: italic;
		color: var(--fg-dim);
		margin-bottom: 0.5rem;
	}
	.curator-note {
		font-size: 0.6875rem;
		color: var(--fg-faint);
		margin-top: 1.5rem;
		line-height: 1.8;
	}

	/* Foreword */
	.foreword {
		margin-bottom: 4rem;
		padding: 2.5rem 0;
		border-top: 1px solid var(--border);
		border-bottom: 1px solid var(--border);
	}
	.foreword h2 {
		font-family: var(--serif);
		font-size: 1.25rem;
		font-weight: 400;
		font-style: italic;
		color: var(--fg-dim);
		margin-bottom: 1.5rem;
	}
	.foreword p {
		font-family: var(--serif);
		font-size: 1rem;
		line-height: 1.9;
		color: var(--fg);
		margin-bottom: 1rem;
		text-indent: 1.5em;
	}
	.foreword p:first-of-type {
		text-indent: 0;
	}
	.foreword-sig {
		text-indent: 0 !important;
		margin-top: 2rem !important;
		font-style: italic;
	}

	/* Table of Contents */
	.toc {
		margin-bottom: 4rem;
	}
	.toc h2 {
		font-family: var(--serif);
		font-size: 1rem;
		font-weight: 400;
		font-style: italic;
		color: var(--fg-dim);
		margin-bottom: 1.5rem;
		letter-spacing: 0.05em;
	}
	.toc ol {
		list-style: none;
		padding: 0;
	}
	.toc li {
		border-bottom: 1px solid var(--border);
	}
	.toc li:first-child {
		border-top: 1px solid var(--border);
	}
	.toc a {
		display: flex;
		align-items: baseline;
		padding: 0.6rem 0;
		border-bottom: none;
		color: var(--fg);
		gap: 1rem;
		transition: color 0.2s;
	}
	.toc a:hover {
		color: var(--accent);
	}
	.toc-num {
		font-size: 0.625rem;
		color: var(--fg-faint);
		letter-spacing: 0.1em;
		min-width: 2rem;
	}
	.toc-title {
		flex: 1;
		font-size: 0.8125rem;
	}
	.toc-date {
		font-size: 0.6875rem;
		color: var(--fg-dim);
		font-style: italic;
		font-family: var(--serif);
	}

	/* Artifacts */
	.artifacts {
		margin-bottom: 4rem;
	}
	.artifact {
		margin-bottom: 0;
		padding-top: 3rem;
		opacity: 0;
		transform: translateY(16px);
		transition: opacity 0.6s ease, transform 0.6s ease;
	}
	.artifact-visible {
		opacity: 1;
		transform: translateY(0);
	}
	.artifact-header {
		margin-bottom: 2rem;
	}
	.artifact-num {
		font-size: 0.5625rem;
		letter-spacing: 0.25em;
		color: var(--fg-faint);
		display: block;
		margin-bottom: 0.5rem;
	}
	.artifact-title-block h2 {
		font-family: var(--serif);
		font-size: 1.5rem;
		font-weight: 400;
		color: var(--fg);
		line-height: 1.4;
	}

	/* Meta */
	.artifact-meta {
		margin-bottom: 2rem;
		padding: 1.25rem 0;
		border-top: 1px solid var(--border);
		border-bottom: 1px solid var(--border);
	}
	.meta-row {
		display: flex;
		gap: 1.5rem;
		padding: 0.2rem 0;
	}
	.meta-label {
		min-width: 90px;
		font-size: 0.625rem;
		letter-spacing: 0.15em;
		color: var(--fg-faint);
		text-transform: uppercase;
		flex-shrink: 0;
	}
	.meta-value {
		font-size: 0.8125rem;
		color: var(--fg-dim);
		font-family: var(--serif);
		font-style: italic;
	}

	/* Body */
	.artifact-body {
		margin-bottom: 2rem;
	}
	.artifact-body p {
		font-family: var(--serif);
		font-size: 1rem;
		line-height: 1.85;
		color: var(--fg);
	}

	/* Evidence */
	.artifact-evidence {
		margin-bottom: 2rem;
		background: var(--bg-inset);
		border: 1px solid var(--border);
		padding: 1.5rem;
		position: relative;
		overflow: hidden;
	}
	.artifact-evidence::after {
		content: '';
		position: absolute;
		inset: 0;
		background: repeating-linear-gradient(
			0deg,
			transparent,
			transparent 2px,
			rgba(255, 255, 255, 0.008) 2px,
			rgba(255, 255, 255, 0.008) 4px
		);
		pointer-events: none;
	}
	.evidence-label {
		font-size: 0.5625rem;
		letter-spacing: 0.2em;
		color: var(--fg-faint);
		margin-bottom: 1rem;
	}
	.evidence-block {
		font-family: var(--mono);
		font-size: 0.75rem;
		line-height: 1.5;
		color: var(--fg-dim);
		overflow-x: auto;
		white-space: pre;
	}

	/* Curator's Note */
	.artifact-note {
		margin-bottom: 2rem;
		padding-left: 1.25rem;
		border-left: 2px solid var(--border-light);
	}
	.note-label {
		font-size: 0.5625rem;
		letter-spacing: 0.2em;
		color: var(--fg-faint);
		text-transform: uppercase;
		display: block;
		margin-bottom: 0.5rem;
	}
	.artifact-note p {
		font-family: var(--serif);
		font-size: 0.9375rem;
		line-height: 1.8;
		color: var(--fg-dim);
		font-style: italic;
	}

	/* Separator */
	.artifact-separator {
		text-align: center;
		padding: 3rem 0 0;
		color: var(--fg-faint);
		letter-spacing: 0.5em;
		font-size: 0.75rem;
	}

	/* Footer */
	.catalog-footer {
		padding-top: 3rem;
	}
	.footer-rule {
		height: 1px;
		background: var(--border);
		margin-bottom: 2rem;
	}
	.colophon {
		text-align: center;
	}
	.colophon p {
		font-size: 0.6875rem;
		letter-spacing: 0.1em;
		line-height: 1.8;
		margin-bottom: 1rem;
	}

	/* Utilities */
	.fg-dim { color: var(--fg-dim); }
	.fg-faint { color: var(--fg-faint); }

	/* Responsive */
	@media (max-width: 600px) {
		.catalog {
			padding: 2rem 1.25rem 4rem;
		}
		.catalog-header {
			flex-direction: column;
			gap: 1rem;
		}
		.catalog-meta {
			align-items: flex-start;
		}
		h1 {
			font-size: 2rem;
		}
		.title-rule {
			margin: 1rem 1rem;
		}
		.meta-row {
			flex-direction: column;
			gap: 0.15rem;
		}
		.meta-label {
			min-width: unset;
		}
		.artifact-evidence {
			padding: 1rem;
		}
		.evidence-block {
			font-size: 0.625rem;
		}
	}
</style>
